on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # recurse submodules
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          system: MINGW64
          install: >-
            git
            base-devel
            mingw64/mingw-w64-x86_64-rust
      - name: Build Libsodium
        run: autoreconf -vfi && ./configure && make
        working-directory: contrib/libsodium
      - name: Test
        run: cargo test --features external-contrib-build
      - name: Build
        run: cargo build --release --features external-contrib-build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cncli-x86_64-pc-windows-gnu.exe
          path: target/release/cncli.exe

  macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # recurse submodules
      - name: Install Dependencies (MacOS)
        run: brew install autoconf automake libtool
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cncli-x86_64-apple-darwin
          path: target/release/cncli

  linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # recurse submodules
      - name: Install Dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cncli-x86_64-unknown-linux-gnu
          path: target/release/cncli