on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build:
    name: Publish
    needs: [ lint ]
    strategy:
      fail-fast: true
      matrix:
        toolchain: [ stable ]
        cross: [ false ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            shell: msys2 {0}
            target: x86_64-pc-windows-gnu
            binary: cncli.exe
          - os: ubuntu-latest
            shell: bash
            target: x86_64-unknown-linux-gnu
            binary: cncli
          - os: macos-latest
            shell: bash
            target: x86_64-apple-darwin
            binary: cncli.exe
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # recurse submodules
      - name: Install Dependencies (Windows MingGW64)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            git
            base-devel
            mingw64/mingw-w64-x86_64-rust
      - name: Install Dependencies (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install autoconf automake libtool
      - name: Install Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev make g++ tmux git jq wget libncursesw5 libtool autoconf
      - name: Build Libsodium
        run: autoreconf -vfi && ./configure && make
        working-directory: contrib/libsodium
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
          default: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: test
          args: --features external-contrib-build --target ${{ matrix.target }}